# Generated by Django 4.0 on 2023-10-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default=None, max_length=250, null=True, upload_to='images')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
